### PR TITLE
Separate templates for RA locations and RAs

### PR DESCRIPTION
**Pull request by arothuis**
* Removes concept of vetting locations in favor of separate concepts (RAs/RA locations)
* Removes concept of institutions with RA locations in favor of institution configuration options
* Fixes flaws in saving institution configuration options and handling commands

### CODE REVIEW

**Comment by DRvanR** [comment]
:+1: looking good! nice cleanup btw.

**Comment by arothuis** [comment]
@DRvanR

**Comment by DRvanR** [comment]
:+1:

**Comment by arothuis** [comment]
@DRvanR, I extracted the email methods so we can add the `showRaaContactInformation` easier later.

**Comment by DRvanR** [comment]
:+1:

**Pull request merged**
