### PR TITLE
Institution configuration option commands

### PR DESCRIPTION
**Pull request by arothuis**

### CODE REVIEW

**Comment by arothuis** [comment]
@DRvanR

**Comment by arothuis** [comment]
@DRvanR

**Comment by DRvanR** [comment]
:+1:

**Comment by DRvanR** [comment]
perhaps `Reconfigure` over `configure`? dunno...

**Comment by arothuis** [comment]
I guess reconfigure makes sense, considering they are already configured by default. 
I'll rename 'em.

**Pull request merged**
