### PR TITLE
Expand the SF identity field for the gateway

### PR DESCRIPTION
**Pull request by DRvanR**

### CODE REVIEW

**Comment by DRvanR** [comment]
@rjkip poke

**Comment by DRvanR** [comment]
scratch that, missing updated version :(

**Comment by DRvanR** [comment]
┬──┬ ノ( ゜-゜ノ)

Now then.

**Comment by rjkip** [comment]
(｡◕‿‿◕｡) :+1:

**Comment by DRvanR** [comment]
@rjkip  (；一_一)

**Comment by rjkip** [comment]
Haha :D Please correct the annotations as wel then ;)

**Comment by DRvanR** [comment]
Done - glad I'm back in the office tomorrow :angry:

**Comment by rjkip** [comment]
:ship:

**Pull request merged**
